/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const AppIndexLazyImport = createFileRoute('/app/')()
const AppLogoutLazyImport = createFileRoute('/app/logout')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AppIndexLazyRoute = AppIndexLazyImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/app/index.lazy').then((d) => d.Route))

const AppLogoutLazyRoute = AppLogoutLazyImport.update({
  id: '/app/logout',
  path: '/app/logout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/app/logout.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/app/logout': {
      id: '/app/logout'
      path: '/app/logout'
      fullPath: '/app/logout'
      preLoaderRoute: typeof AppLogoutLazyImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/app/logout': typeof AppLogoutLazyRoute
  '/app': typeof AppIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/app/logout': typeof AppLogoutLazyRoute
  '/app': typeof AppIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/app/logout': typeof AppLogoutLazyRoute
  '/app/': typeof AppIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app/logout' | '/app'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app/logout' | '/app'
  id: '__root__' | '/' | '/app/logout' | '/app/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AppLogoutLazyRoute: typeof AppLogoutLazyRoute
  AppIndexLazyRoute: typeof AppIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AppLogoutLazyRoute: AppLogoutLazyRoute,
  AppIndexLazyRoute: AppIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app/logout",
        "/app/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/app/logout": {
      "filePath": "app/logout.lazy.tsx"
    },
    "/app/": {
      "filePath": "app/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
